name: "GPSD Proxy"
version: "1.1.0"
slug: "gpsd_proxy"
description: "Connects to a USB GPS antenna and serves the GPSD protocol on port 2947"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
url: "https://github.com/e4t-home/ha-addons/tree/main/gpsd-proxy"
startup: "system"
boot: "auto"
ports:
  2947/tcp: 2947
ports_description:
  2947/tcp: "GPSD protocol port"
uart: true
options:
  device: "/dev/ttyUSB0"
schema:
  device: device(subsystem=tty)
